### ISSUE TITLE
monster_abilities.lua - 1278+

### ISSUE THREAD

**Issue by Byrth** [Windower/ResourceExtractor#35]
For some reason monster_abilities extraction stops at 1278. It could be that the other ones are in a different file, but higher ones have been in game for quite a while now ("Lava Spit" being an example).

**Comment by cassierose** [comment]
I realize that monstrosity is not a high priority but I thought I'd let you know the issue I've been having. I recently started doing monstrosity again and noticed that I'm not able to use certain monster abilities and keep getting the message /ma error 17261001 or /ma 295691 and a few other numbers depending on the mob. I found that while shortcuts is loaded any monster ability that can be learned as a spell by BLU will trigger this error code. As long as I don't have shortcuts loaded while under monstrosity everything works fine. I don't expect this issue to be fixed, this post is more of an fyi

**Comment by Byrth** [comment]
I've come to believe that SE created another Monstrosity .dat that maps monster skill ability IDs to strings, and that's likely why they stopped updating this .dat.

**Comment by Byrth** [comment]
> [9:15 PM] Devi Ltti: both of the issues referenced are due to using the wrong dat to build the resource. theres one for abilities (which is what the issue is) and theres one for actual monsters using their skills
> [9:16 PM] Devi Ltti: https://github.com/Windower/ResourceExtractor/blob/master/Program.cs#L457
> [9:17 PM] Devi Ltti: monstrosity abilities are in the same dat as the rest of the ability data and line up with the names
> [9:19 PM] Byrth: Awesome
> [9:45 PM] Byrth: Do you have the .dat address of the other one?(edited)
> [9:47 PM] Devi Ltti: yeah its the same as its always been ROM\181\72.DAT contains the names, ROM\118\114.DAT contains the data
> [9:48 PM] Devi Ltti: currently the resource is built from parsing the monster skill names from ROM\27\80.DAT

eyyyy

**Comment by Byrth** [comment]
The problem here was that we were parsing information out if the normal abilities .dat, but then overwriting the strings with information from the true monster_abilities .dat despite the fact that their enums did not line up (anymore.)

The fix is here: https://github.com/Windower/ResourceExtractor/pull/77
which splits the two dats apart and makes them separate resources so their different enum orders can be respected.
