### ISSUE TITLE
monstrosity.lua - shuffled tp_moves

### ISSUE THREAD

**Issue by Byrth** [Windower/ResourceExtractor#36]
I'm not sure why, but some tp_moves seem to be shuffled. For instance, Funguars have Mandragora TP moves. It's not always perfect transposition like that, though. Gnoles have Deal Out (Cardian), Nihility Song / Back Heel / Jettatura / Choke Breath / Fantod (Hippogryph), and Blow (Goobbue).

I think any substitutions are coincidental, but the fact that they're all valid IDs is probably useful information.

**Comment by cassierose** [comment]
I realize that monstrosity is not a high priority but I thought I'd let you know the issue I've been having. I recently started doing monstrosity again and noticed that I'm not able to use certain monster abilities and keep getting the message /ma error 17261001 or /ma 295691 and a few other numbers depending on the mob. I found that while shortcuts is loaded any monster ability that can be learned as a spell by BLU will trigger this error code. As long as I don't have shortcuts loaded while under monstrosity everything works fine. I don't expect this issue to be fixed, this post is more of an fyi (i hope i posted under the correct post that applies to monstrosity)

**Comment by IryokuChevalier** [comment]
@cassierose: This sounds like a Shortcuts issue, not a problem with the Resources Extractor. I think @kelhor is maintaining Byrth's addons now.

**Comment by kelhor** [comment]
I'm out of town until Tuesday; I can take a look then, if no one has solved it before then.

**Comment by cassierose** [comment]
Hardly anyone does monstrosity these days anymore but I just wanted to share my observation in case anyone else has the same issue and let them know that unloading shortcuts did the trick in my case.

**Comment by Byrth** [comment]
Shortcuts is working as intended, but the resources for Monstrosity TP moves are messed up as described in the original post. As such, it doesn't recognize any possible valid monster TP move and defaults to assuming the move is blue magic.

**Comment by cassierose** [comment]
Thanks :)

**Comment by Byrth** [comment]
This is fixed now!
